use payrail_output::config::OutputConfig;
use payrail_output::{format, symbols};
use serde::Serialize;
use std::fs;
use std::path::Path;

#[derive(Debug)]
pub enum InitError {
    AlreadyInitialized,
    NoProvider,
    Io(String),
}

impl std::fmt::Display for InitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::AlreadyInitialized => write!(
                f,
                "[INIT_EXISTS] Project already initialized [Remove payrail.config.yaml to re-initialize]"
            ),
            Self::NoProvider => write!(
                f,
                "[INIT_NO_PROVIDER] No provider specified [Use: payrail init --provider <name>]"
            ),
            Self::Io(msg) => write!(f, "[INIT_IO] {msg}"),
        }
    }
}

impl std::error::Error for InitError {}

pub fn format_error(config: &OutputConfig, err: &InitError) -> String {
    let (what, why, action) = match err {
        InitError::AlreadyInitialized => (
            "Already initialized".to_owned(),
            "payrail.config.yaml already exists".to_owned(),
            "Remove payrail.config.yaml to re-initialize".to_owned(),
        ),
        InitError::NoProvider => (
            "No provider specified".to_owned(),
            "The --provider flag is required".to_owned(),
            "Use: payrail init --provider <name>".to_owned(),
        ),
        InitError::Io(msg) => (
            "I/O error".to_owned(),
            msg.clone(),
            "Check file paths and permissions".to_owned(),
        ),
    };

    if config.is_json() {
        let val = serde_json::json!({
            "status": "error",
            "error": what,
            "reason": why,
            "help": action,
        });
        serde_json::to_string(&val).unwrap()
    } else {
        format::error_message(config, &what, &why, &action)
    }
}

#[derive(Serialize)]
struct InitReport {
    provider: String,
    files_created: Vec<String>,
    language: String,
    framework: String,
}

/// Initialize a PayRail project scaffold.
///
/// `project_dir` is the root directory to create files in (defaults to ".").
pub fn init_project(
    provider: Option<&str>,
    lang: Option<&str>,
    framework: Option<&str>,
    config: &OutputConfig,
) -> Result<(), InitError> {
    init_project_in(Path::new("."), provider, lang, framework, config)
}

fn init_project_in(
    project_dir: &Path,
    provider: Option<&str>,
    lang: Option<&str>,
    framework: Option<&str>,
    config: &OutputConfig,
) -> Result<(), InitError> {
    let provider = provider.ok_or(InitError::NoProvider)?;

    let config_path = project_dir.join("payrail.config.yaml");
    if config_path.exists() {
        return Err(InitError::AlreadyInitialized);
    }

    // Auto-detect language from project files if --lang not provided
    let detected_lang = lang.unwrap_or_else(|| {
        if project_dir.join("Cargo.toml").exists() {
            "rust"
        } else if project_dir.join("go.mod").exists() {
            "go"
        } else if project_dir.join("requirements.txt").exists()
            || project_dir.join("pyproject.toml").exists()
        {
            "python"
        } else if project_dir.join("package.json").exists() {
            "typescript"
        } else {
            "rust"
        }
    });

    // Auto-detect framework from project files if --framework not provided
    let detected_framework = framework.unwrap_or_else(|| {
        if project_dir.join("package.json").exists()
            && let Ok(content) = fs::read_to_string(project_dir.join("package.json"))
        {
            if content.contains("\"next\"") {
                return "nextjs";
            }
            if content.contains("\"express\"") {
                return "express";
            }
        }
        "standalone"
    });

    let config_content = format!(
        "# PayRail Configuration\n# Generated by `payrail init`\n\nprovider: {provider}\nlanguage: {detected_lang}\nframework: {detected_framework}\n\n# Knowledge pack location\nknowledge_packs: knowledge-packs/\n\n# Adapter output location\nadapters: src/adapters/\n"
    );

    fs::write(&config_path, &config_content).map_err(|e| InitError::Io(e.to_string()))?;

    let env_content = match provider {
        "peach-payments" => "# PayRail Environment Variables\n# Copy to .env and fill in values\n\nPEACH_SANDBOX_API_KEY=\nPEACH_SANDBOX_ENTITY_ID=\nPEACH_SANDBOX_WEBHOOK_SECRET=\n\nPAYRAIL_LOG_LEVEL=info\n".to_owned(),
        "startbutton" => "# PayRail Environment Variables\n# Copy to .env and fill in values\n\nSTARTBUTTON_SANDBOX_API_KEY=\nSTARTBUTTON_SANDBOX_WEBHOOK_SECRET=\n\nPAYRAIL_LOG_LEVEL=info\n".to_owned(),
        _ => {
            let upper = provider.replace('-', "_").to_uppercase();
            format!(
                "# PayRail Environment Variables\n# Copy to .env and fill in values\n\n{upper}_SANDBOX_API_KEY=\n{upper}_SANDBOX_WEBHOOK_SECRET=\n\nPAYRAIL_LOG_LEVEL=info\n"
            )
        }
    };

    fs::write(project_dir.join(".env.example"), &env_content)
        .map_err(|e| InitError::Io(e.to_string()))?;

    fs::create_dir_all(project_dir.join("src/adapters"))
        .map_err(|e| InitError::Io(e.to_string()))?;

    fs::create_dir_all(project_dir.join("knowledge-packs"))
        .map_err(|e| InitError::Io(e.to_string()))?;

    let files_created = vec![
        "payrail.config.yaml".to_owned(),
        ".env.example".to_owned(),
        "src/adapters/".to_owned(),
        "knowledge-packs/".to_owned(),
    ];

    if config.is_json() {
        let report = InitReport {
            provider: provider.to_owned(),
            files_created: files_created.clone(),
            language: detected_lang.to_owned(),
            framework: detected_framework.to_owned(),
        };
        println!("{}", serde_json::to_string(&report).unwrap());
    } else {
        println!(
            "{}",
            format::summary_line(
                config,
                &format!("{} PayRail Initialized", symbols::pass_symbol(config))
            )
        );
        println!();
        println!("{}", format::section_header(config, "Project:"));
        println!(
            "{}",
            format::detail_line(&format!("Provider: {provider}"), 2)
        );
        println!(
            "{}",
            format::detail_line(&format!("Language: {detected_lang}"), 2)
        );
        println!(
            "{}",
            format::detail_line(&format!("Framework: {detected_framework}"), 2)
        );
        println!();
        println!("{}", format::section_header(config, "Created:"));
        for f in &files_created {
            println!("{}", format::detail_line(f, 2));
        }
        println!();
        println!(
            "{}",
            format::help_line(
                config,
                &format!(
                    "Run `payrail knowledge init {}` to create a knowledge pack",
                    provider
                )
            )
        );
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn test_config() -> OutputConfig {
        OutputConfig::from_env(false, true, false, true)
    }

    fn json_config() -> OutputConfig {
        OutputConfig::from_env(true, false, false, false)
    }

    fn temp_dir() -> PathBuf {
        let dir = std::env::temp_dir().join(format!("payrail-init-test-{}", ulid::Ulid::new()));
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn init_requires_provider() {
        let dir = temp_dir();
        let result = init_project_in(&dir, None, None, None, &test_config());
        assert!(result.is_err());
        match result.unwrap_err() {
            InitError::NoProvider => {}
            other => panic!("expected NoProvider, got: {other}"),
        }
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn init_creates_config_file() {
        let dir = temp_dir();
        init_project_in(&dir, Some("test-provider"), None, None, &test_config()).unwrap();
        assert!(dir.join("payrail.config.yaml").exists());
        assert!(dir.join(".env.example").exists());
        assert!(dir.join("src/adapters").is_dir());
        assert!(dir.join("knowledge-packs").is_dir());
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn init_rejects_already_initialized() {
        let dir = temp_dir();
        init_project_in(&dir, Some("test-provider"), None, None, &test_config()).unwrap();
        let result = init_project_in(&dir, Some("test-provider"), None, None, &test_config());
        assert!(result.is_err());
        match result.unwrap_err() {
            InitError::AlreadyInitialized => {}
            other => panic!("expected AlreadyInitialized, got: {other}"),
        }
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn init_config_contains_provider() {
        let dir = temp_dir();
        init_project_in(&dir, Some("peach-payments"), None, None, &test_config()).unwrap();
        let content = fs::read_to_string(dir.join("payrail.config.yaml")).unwrap();
        assert!(content.contains("peach-payments"));
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn init_env_example_has_provider_vars() {
        let dir = temp_dir();
        init_project_in(&dir, Some("peach-payments"), None, None, &test_config()).unwrap();
        let content = fs::read_to_string(dir.join(".env.example")).unwrap();
        assert!(content.contains("PEACH_SANDBOX_API_KEY"));
        assert!(content.contains("PEACH_SANDBOX_ENTITY_ID"));
        assert!(content.contains("PEACH_SANDBOX_WEBHOOK_SECRET"));
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn format_error_text() {
        let cfg = test_config();
        let err = InitError::NoProvider;
        let formatted = format_error(&cfg, &err);
        assert!(formatted.contains("No provider"));
    }

    #[test]
    fn format_error_json_valid() {
        let cfg = json_config();
        let err = InitError::NoProvider;
        let formatted = format_error(&cfg, &err);
        let parsed: serde_json::Value = serde_json::from_str(&formatted).unwrap();
        assert_eq!(parsed["status"], "error");
    }
}
