import type { CompiledFact } from "../knowledge/compiler.js";
import type { CodebaseFingerprint } from "../fingerprint/conventions.js";
import type { PayRailConfig } from "../config/schema.js";
import { CANONICAL_STATES, type GeneratedFile } from "./pipeline.js";

interface ClassifiedFacts {
  generate: CompiledFact[];
  verify: CompiledFact[];
  refused: CompiledFact[];
}

interface GenerationThresholds {
  generate: number;
  verifyMin: number;
}

function pascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join("");
}

function verifyComment(fact: CompiledFact, what: string): string {
  return `// VERIFY: ${what} (confidence: ${fact.confidence_score}, source: ${fact.source}, check: Verify against provider documentation)`;
}

function buildStatusMappings(facts: ClassifiedFacts, thresholds: GenerationThresholds): string {
  const statusFacts = [
    ...facts.generate.filter((f) => f.category === "status_codes"),
    ...facts.verify.filter((f) => f.category === "status_codes"),
  ];

  if (statusFacts.length === 0) {
    return CANONICAL_STATES.map(
      (state) =>
        `  // VERIFY: Status mapping for ${state} (confidence: 0, source: none, check: Add provider-specific status code mapping)\n  // "${state}": "UNMAPPED",`,
    ).join("\n");
  }

  const lines: string[] = [];
  for (const fact of statusFacts) {
    const val = fact.value as { provider_code: string; canonical_state: string; description: string };
    const isVerify = fact.confidence_score < thresholds.generate;
    if (isVerify) {
      lines.push(`  ${verifyComment(fact, `Status mapping: ${val.provider_code} -> ${val.canonical_state}`)}`);
    }
    lines.push(`  "${val.provider_code}": "${val.canonical_state}", // ${val.description}`);
  }
  return lines.join("\n");
}

function buildEndpointMethods(facts: ClassifiedFacts, providerClass: string, thresholds: GenerationThresholds): string {
  const endpointFacts = [
    ...facts.generate.filter((f) => f.category === "endpoints"),
    ...facts.verify.filter((f) => f.category === "endpoints"),
  ];

  if (endpointFacts.length === 0) {
    return [
      `    // VERIFY: No endpoint facts available (confidence: 0, source: none, check: Add endpoint details to knowledge pack)`,
      `    throw new Error("${providerClass}: endpoint configuration missing — add to knowledge pack");`,
    ].join("\n");
  }

  const lines: string[] = [];
  for (const fact of endpointFacts) {
    const val = fact.value as { url: string; method: string; description: string; parameters: string[] };
    const isVerify = fact.confidence_score < thresholds.generate;
    if (isVerify) {
      lines.push(`    ${verifyComment(fact, `Endpoint: ${val.method} ${val.url}`)}`);
    }
    lines.push(`    // ${val.description}`);
    lines.push(`    // ${val.method} ${val.url} — params: ${val.parameters.join(", ") || "none"}`);
  }
  return lines.join("\n");
}

function buildWebhookEventMap(facts: ClassifiedFacts, thresholds: GenerationThresholds): string {
  const webhookFacts = [
    ...facts.generate.filter((f) => f.category === "webhooks"),
    ...facts.verify.filter((f) => f.category === "webhooks"),
  ];

  if (webhookFacts.length === 0) {
    return `  // VERIFY: No webhook event facts available (confidence: 0, source: none, check: Add webhook event mappings to knowledge pack)`;
  }

  const lines: string[] = [];
  for (const fact of webhookFacts) {
    const val = fact.value as { event_name: string; description: string };
    const isVerify = fact.confidence_score < thresholds.generate;
    if (isVerify) {
      lines.push(`  ${verifyComment(fact, `Webhook event: ${val.event_name}`)}`);
    }
    lines.push(`  "${val.event_name}": true, // ${val.description}`);
  }
  return lines.join("\n");
}

function generateTsAdapter(
  provider: string,
  facts: ClassifiedFacts,
  _fingerprint: CodebaseFingerprint | null,
  thresholds: GenerationThresholds,
): string {
  const className = `${pascalCase(provider)}Adapter`;
  const statusMappings = buildStatusMappings(facts, thresholds);
  const endpointMethods = buildEndpointMethods(facts, className, thresholds);
  const webhookEventMap = buildWebhookEventMap(facts, thresholds);

  return `/**
 * ${className} — Payment adapter for ${pascalCase(provider)}
 *
 * Auto-generated by PayRail MCP generate_adapter tool.
 * Review all VERIFY markers before production use.
 */

// Canonical payment states from PayRail engine
type CanonicalState = "Created" | "Authorized" | "Captured" | "Refunded" | "Voided" | "Failed" | "Expired" | "Pending3ds";

interface PaymentCommand {
  type: "charge" | "authorize" | "capture" | "refund" | "void";
  amount: number; // Integer cents — never floating point
  currency: string;
  idempotencyKey: string;
  metadata?: Record<string, string>;
}

interface PaymentEvent {
  state: CanonicalState;
  providerRef: string;
  amount: number;
  currency: string;
  raw: unknown;
}

interface WebhookEvent {
  eventType: string;
  payload: unknown;
}

interface SignatureConfig {
  header: string;
  algorithm: string;
  secret: string;
}

// Provider status code -> canonical state mapping
const STATUS_MAP: Record<string, CanonicalState> = {
${statusMappings}
};

// Known webhook event types
const WEBHOOK_EVENTS: Record<string, boolean> = {
${webhookEventMap}
};

export class ${className} {
  private readonly baseUrl: string;
  private readonly apiKey: string;

  constructor(baseUrl: string, apiKey: string) {
    this.baseUrl = baseUrl;
    this.apiKey = apiKey;
  }

  /**
   * Execute a payment command against the provider API.
   * Amount is always in integer cents — never floating point.
   */
  async execute(command: PaymentCommand): Promise<PaymentEvent> {
${endpointMethods}

    // Amount handling: integer cents to provider format
    // PayRail enforces integer cents internally — convert to provider's expected format
    const providerAmount = (command.amount / 100).toFixed(2);

    const response = await fetch(\`\${this.baseUrl}/payments\`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": \`Bearer \${this.apiKey}\`,
      },
      body: JSON.stringify({
        amount: providerAmount,
        currency: command.currency,
        merchantTransactionId: command.idempotencyKey,
        ...command.metadata,
      }),
    });

    const data = await response.json() as Record<string, unknown>;
    const providerCode = String(data.result ?? data.status ?? "unknown");
    const state = STATUS_MAP[providerCode] ?? "Failed";

    return {
      state,
      providerRef: String(data.id ?? ""),
      amount: command.amount,
      currency: command.currency,
      raw: data,
    };
  }

  /**
   * Translate a provider webhook into a canonical PayRail event.
   * Uses raw body for signature verification — never parsed JSON.
   */
  translateWebhook(event: WebhookEvent): PaymentEvent {
    const payload = event.payload as Record<string, unknown>;
    const eventType = event.eventType;

    if (!WEBHOOK_EVENTS[eventType]) {
      return {
        state: "Failed",
        providerRef: String(payload.id ?? ""),
        amount: 0,
        currency: "",
        raw: payload,
      };
    }

    // Parse amount from provider format (decimal string) to integer cents
    const rawAmount = String(payload.amount ?? "0");
    const amount = Math.round(parseFloat(rawAmount) * 100);

    const providerCode = String(payload.result ?? payload.status ?? "unknown");
    const state = STATUS_MAP[providerCode] ?? "Failed";

    return {
      state,
      providerRef: String(payload.id ?? ""),
      amount,
      currency: String(payload.currency ?? ""),
      raw: payload,
    };
  }

  /**
   * Webhook signature verification configuration.
   * Signature is computed over the raw request body — not parsed JSON.
   */
  signatureConfig(): SignatureConfig {
    return {
      header: "x-signature",
      algorithm: "sha256",
      secret: process.env.${provider.toUpperCase().replace(/-/g, "_")}_WEBHOOK_SECRET ?? "",
    };
  }
}

/**
 * Parse amount string to integer cents.
 * "100.50" -> 10050, "42" -> 4200
 * PayRail rule: never use floating point for money.
 */
export function parseAmountToCents(amount: string): number {
  return Math.round(parseFloat(amount) * 100);
}
`;
}

function generateTsWebhookHandler(
  provider: string,
  _facts: ClassifiedFacts,
  _fingerprint: CodebaseFingerprint | null,
): string {
  const className = `${pascalCase(provider)}Adapter`;

  return `/**
 * Webhook handler for ${pascalCase(provider)}
 *
 * Auto-generated by PayRail MCP generate_adapter tool.
 * Signature verification uses raw body — never parsed JSON.
 */
import { ${className} } from "./${provider}-adapter";
import { createHmac, timingSafeEqual } from "node:crypto";

const adapter = new ${className}(
  process.env.${provider.toUpperCase().replace(/-/g, "_")}_BASE_URL ?? "",
  process.env.${provider.toUpperCase().replace(/-/g, "_")}_API_KEY ?? "",
);

/**
 * Verify webhook signature using raw request body.
 * IMPORTANT: Use raw body, not JSON.stringify(parsed) — they differ.
 */
export function verifySignature(rawBody: string, signature: string): boolean {
  const config = adapter.signatureConfig();
  const expected = createHmac(config.algorithm, config.secret)
    .update(rawBody)
    .digest("hex");
  // Constant-time comparison to prevent timing side-channel attacks
  const a = Buffer.from(expected, "utf-8");
  const b = Buffer.from(signature, "utf-8");
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

/**
 * Handle incoming webhook from ${pascalCase(provider)}.
 * Idempotency key format: ${provider}:{merchantId}:webhook:{eventId}
 */
export function handleWebhook(rawBody: string, headers: Record<string, string>): {
  verified: boolean;
  event: ReturnType<typeof adapter.translateWebhook> | null;
  idempotencyKey: string | null;
} {
  const config = adapter.signatureConfig();
  const signature = headers[config.header] ?? "";

  if (!verifySignature(rawBody, signature)) {
    return { verified: false, event: null, idempotencyKey: null };
  }

  const parsed = JSON.parse(rawBody) as Record<string, unknown>;
  const eventType = String(parsed.type ?? parsed.event_type ?? "unknown");
  const eventId = String(parsed.id ?? "");
  const merchantId = String((parsed.payload as Record<string, unknown>)?.merchantTransactionId ?? "unknown");

  // Idempotency key: {provider}:{merchantId}:webhook:{eventId}
  // TTL: 30 days (configured in PayRail engine)
  const idempotencyKey = \`${provider}:\${merchantId}:webhook:\${eventId}\`;

  const event = adapter.translateWebhook({ eventType, payload: parsed.payload ?? parsed });

  return { verified: true, event, idempotencyKey };
}
`;
}

function generateTsConformanceTests(
  provider: string,
  _facts: ClassifiedFacts,
  fingerprint: CodebaseFingerprint | null,
): string {
  const className = `${pascalCase(provider)}Adapter`;
  const testFramework = fingerprint?.testFramework.value ?? "vitest";

  const importLine = testFramework === "jest"
    ? `import { ${className} } from "./${provider}-adapter";`
    : `import { describe, it, expect } from "${testFramework}";\nimport { ${className} } from "./${provider}-adapter";`;

  return `/**
 * Conformance test suite for ${className}
 *
 * Auto-generated by PayRail MCP generate_adapter tool.
 * Tests all 8 canonical state transitions.
 */
${importLine}

describe("${className}", () => {
${CANONICAL_STATES.map(
    (state) => `  it("maps provider status to ${state}", () => {
    // TODO: Add provider-specific status code that maps to ${state}
    // const adapter = new ${className}("https://sandbox.example.com", "test-key");
    // const event = adapter.translateWebhook({ eventType: "payment.${state.toLowerCase()}", payload: { ... } });
    // expect(event.state).toBe("${state}");
    expect(true).toBe(true); // Placeholder — fill in with provider-specific mappings
  });`,
  ).join("\n\n")}

  it("parses amount string to integer cents", () => {
    // PayRail rule: never floating point for money
    const adapter = new ${className}("https://sandbox.example.com", "test-key");
    const event = adapter.translateWebhook({
      eventType: "payment.captured",
      payload: { amount: "100.50", currency: "USD", id: "test-ref", result: "000.000" },
    });
    expect(event.amount).toBe(10050);
  });

  it("returns SignatureConfig with expected fields", () => {
    const adapter = new ${className}("https://sandbox.example.com", "test-key");
    const config = adapter.signatureConfig();
    expect(config.header).toBeDefined();
    expect(config.algorithm).toBeDefined();
  });
});
`;
}

function generateTsIdempotencyConfig(provider: string): string {
  return `/**
 * Idempotency configuration for ${pascalCase(provider)}
 *
 * Auto-generated by PayRail MCP generate_adapter tool.
 * Key format: {provider}:{merchantId}:webhook:{eventId}
 * TTL: 30 days — matches PayRail engine default.
 */
export const idempotencyConfig = {
  provider: "${provider}",
  keyFormat: "${provider}:{merchantId}:webhook:{eventId}",
  ttlSeconds: 30 * 24 * 60 * 60, // 30 days
  /**
   * Build idempotency key from webhook event data.
   * Fail-closed: if key cannot be built, defer processing rather than process unsafely.
   */
  buildKey(merchantId: string, eventId: string): string {
    if (!merchantId || !eventId) {
      throw new Error("[IDEMPOTENCY_KEY] Cannot build key: missing merchantId or eventId. Defer processing.");
    }
    return \`${provider}:\${merchantId}:webhook:\${eventId}\`;
  },
};
`;
}

export function generateAdapterFiles(
  provider: string,
  targetLanguage: "typescript" | "rust",
  facts: ClassifiedFacts,
  fingerprint: CodebaseFingerprint | null,
  config: PayRailConfig,
): GeneratedFile[] {
  if (targetLanguage === "rust") {
    // Rust generation is secondary — return stub with VERIFY markers
    return [{
      name: `${provider}_adapter.rs`,
      path: `src/adapters/${provider}_adapter.rs`,
      content: `// VERIFY: Rust adapter generation is experimental (confidence: 0.5, source: inferred, check: Review generated code carefully)\n// TODO: Implement Rust adapter for ${provider}\nunimplemented!()`,
      lineCount: 3,
    }];
  }

  const thresholds: GenerationThresholds = {
    generate: config.confidence.generate,
    verifyMin: config.confidence.verify_min,
  };
  const adapterContent = generateTsAdapter(provider, facts, fingerprint, thresholds);
  const webhookContent = generateTsWebhookHandler(provider, facts, fingerprint);
  const testContent = generateTsConformanceTests(provider, facts, fingerprint);
  const idempotencyContent = generateTsIdempotencyConfig(provider);

  const files: GeneratedFile[] = [
    {
      name: `${provider}-adapter.ts`,
      path: `src/adapters/${provider}-adapter.ts`,
      content: adapterContent,
      lineCount: adapterContent.split("\n").length,
    },
    {
      name: `${provider}-webhook.ts`,
      path: `src/adapters/${provider}-webhook.ts`,
      content: webhookContent,
      lineCount: webhookContent.split("\n").length,
    },
    {
      name: `${provider}-adapter.test.ts`,
      path: `src/adapters/${provider}-adapter.test.ts`,
      content: testContent,
      lineCount: testContent.split("\n").length,
    },
    {
      name: `${provider}-idempotency.ts`,
      path: `src/adapters/${provider}-idempotency.ts`,
      content: idempotencyContent,
      lineCount: idempotencyContent.split("\n").length,
    },
  ];

  return files;
}
