use std::fmt;
use std::str::FromStr;

use serde::{Deserialize, Serialize};

/// A payment identifier: `pay_` prefix followed by a ULID (Crockford Base32).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct PaymentId(String);

impl PaymentId {
    const PREFIX: &'static str = "pay_";

    /// Generates a new unique payment ID with `pay_` prefix.
    pub fn new() -> Self {
        let ulid = ulid::Ulid::new();
        Self(format!("{}{}", Self::PREFIX, ulid))
    }

    /// Returns the string representation including the `pay_` prefix.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Default for PaymentId {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
impl PaymentId {
    pub(crate) fn from_ulid(ulid: ulid::Ulid) -> Self {
        Self(format!("{}{}", Self::PREFIX, ulid))
    }
}

impl fmt::Display for PaymentId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl FromStr for PaymentId {
    type Err = IdParseError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if !s.starts_with(Self::PREFIX) {
            return Err(IdParseError::MissingPrefix {
                expected: Self::PREFIX,
                got: s.to_owned(),
            });
        }
        let ulid_part = &s[Self::PREFIX.len()..];
        // Validate the ULID portion parses correctly
        ulid::Ulid::from_str(ulid_part).map_err(|_| IdParseError::InvalidUlid {
            input: s.to_owned(),
        })?;
        Ok(Self(s.to_owned()))
    }
}

impl TryFrom<String> for PaymentId {
    type Error = IdParseError;

    fn try_from(s: String) -> Result<Self, Self::Error> {
        s.parse()
    }
}

impl From<PaymentId> for String {
    fn from(id: PaymentId) -> Self {
        id.0
    }
}

/// An event identifier: `evt_` prefix followed by a ULID (Crockford Base32).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct EventId(String);

impl EventId {
    const PREFIX: &'static str = "evt_";

    /// Generates a new unique event ID with `evt_` prefix.
    pub fn new() -> Self {
        let ulid = ulid::Ulid::new();
        Self(format!("{}{}", Self::PREFIX, ulid))
    }

    /// Returns the string representation including the `evt_` prefix.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Default for EventId {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
impl EventId {
    pub(crate) fn from_ulid(ulid: ulid::Ulid) -> Self {
        Self(format!("{}{}", Self::PREFIX, ulid))
    }
}

impl fmt::Display for EventId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl FromStr for EventId {
    type Err = IdParseError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if !s.starts_with(Self::PREFIX) {
            return Err(IdParseError::MissingPrefix {
                expected: Self::PREFIX,
                got: s.to_owned(),
            });
        }
        let ulid_part = &s[Self::PREFIX.len()..];
        ulid::Ulid::from_str(ulid_part).map_err(|_| IdParseError::InvalidUlid {
            input: s.to_owned(),
        })?;
        Ok(Self(s.to_owned()))
    }
}

impl TryFrom<String> for EventId {
    type Error = IdParseError;

    fn try_from(s: String) -> Result<Self, Self::Error> {
        s.parse()
    }
}

impl From<EventId> for String {
    fn from(id: EventId) -> Self {
        id.0
    }
}

/// Errors from parsing prefixed ID strings.
#[derive(Debug, Clone, thiserror::Error)]
pub enum IdParseError {
    /// The input string does not start with the expected prefix.
    #[error(
        "[ID_MISSING_PREFIX] Expected prefix '{expected}' [GOT '{got}'] [Use PaymentId::new() or EventId::new() to generate valid IDs]"
    )]
    MissingPrefix {
        /// The expected prefix (e.g., `"pay_"`).
        expected: &'static str,
        /// The actual input string.
        got: String,
    },

    /// The ULID portion of the input is not valid Crockford Base32.
    #[error(
        "[ID_INVALID_ULID] Invalid ULID in '{input}' [Malformed Crockford Base32] [Ensure ID was generated by PayRail]"
    )]
    InvalidUlid {
        /// The full invalid input string.
        input: String,
    },
}

#[cfg(test)]
mod tests {
    use super::*;

    // -- PaymentId tests --

    #[test]
    fn payment_id_has_prefix() {
        let id = PaymentId::new();
        assert!(id.as_str().starts_with("pay_"), "got: {}", id);
    }

    #[test]
    fn payment_id_display() {
        let id = PaymentId::new();
        let display = id.to_string();
        assert!(display.starts_with("pay_"));
        // pay_ (4) + ULID (26) = 30 chars
        assert_eq!(display.len(), 30);
    }

    #[test]
    fn payment_id_sortable() {
        // Deterministic: use fixed ULIDs with explicitly different timestamps
        let ulid1 = ulid::Ulid::from_parts(1000, 1);
        let ulid2 = ulid::Ulid::from_parts(2000, 1);
        let id1 = PaymentId::from_ulid(ulid1);
        let id2 = PaymentId::from_ulid(ulid2);
        // Later timestamp => lexicographically greater
        assert!(id2.as_str() > id1.as_str());
    }

    #[test]
    fn payment_id_parse_valid() {
        let id = PaymentId::new();
        let parsed: PaymentId = id.as_str().parse().unwrap();
        assert_eq!(id, parsed);
    }

    #[test]
    fn payment_id_parse_missing_prefix() {
        let result: Result<PaymentId, _> = "evt_01HXYZ".parse();
        assert!(result.is_err());
    }

    #[test]
    fn payment_id_parse_invalid_ulid() {
        let result: Result<PaymentId, _> = "pay_NOT_VALID".parse();
        assert!(result.is_err());
    }

    #[test]
    fn payment_id_serde_round_trip() {
        let id = PaymentId::new();
        let json = serde_json::to_string(&id).unwrap();
        let parsed: PaymentId = serde_json::from_str(&json).unwrap();
        assert_eq!(id, parsed);
    }

    // -- EventId tests --

    #[test]
    fn event_id_has_prefix() {
        let id = EventId::new();
        assert!(id.as_str().starts_with("evt_"), "got: {}", id);
    }

    #[test]
    fn event_id_display() {
        let id = EventId::new();
        let display = id.to_string();
        assert!(display.starts_with("evt_"));
        assert_eq!(display.len(), 30);
    }

    #[test]
    fn event_id_sortable() {
        // Deterministic: use fixed ULIDs with explicitly different timestamps
        let ulid1 = ulid::Ulid::from_parts(1000, 1);
        let ulid2 = ulid::Ulid::from_parts(2000, 1);
        let id1 = EventId::from_ulid(ulid1);
        let id2 = EventId::from_ulid(ulid2);
        assert!(id2.as_str() > id1.as_str());
    }

    #[test]
    fn event_id_parse_valid() {
        let id = EventId::new();
        let parsed: EventId = id.as_str().parse().unwrap();
        assert_eq!(id, parsed);
    }

    #[test]
    fn event_id_parse_missing_prefix() {
        let result: Result<EventId, _> = "pay_01HXYZ".parse();
        assert!(result.is_err());
    }

    #[test]
    fn event_id_serde_round_trip() {
        let id = EventId::new();
        let json = serde_json::to_string(&id).unwrap();
        let parsed: EventId = serde_json::from_str(&json).unwrap();
        assert_eq!(id, parsed);
    }

    #[test]
    fn event_id_try_from_string() {
        let id = EventId::new();
        let s = id.to_string();
        let parsed = EventId::try_from(s).unwrap();
        assert_eq!(id, parsed);
    }

    #[test]
    fn payment_id_uniqueness_100() {
        let ids: std::collections::HashSet<String> =
            (0..100).map(|_| PaymentId::new().to_string()).collect();
        assert_eq!(ids.len(), 100, "Expected 100 unique PaymentIds");
    }

    #[test]
    fn id_default_trait() {
        let pid = PaymentId::default();
        assert!(pid.as_str().starts_with("pay_"));
        assert_eq!(pid.as_str().len(), 30);

        let eid = EventId::default();
        assert!(eid.as_str().starts_with("evt_"));
        assert_eq!(eid.as_str().len(), 30);
    }
}
